### ISSUE TITLE
Encore TS

### ISSUE THREAD

**Issue by MElkmeshi** [fernandoslim/odoo-jsonrpc#12]
when I try to use OdooJSONRpc in Encore TS Project I get this error
PS C:\Users\melkmeshi\Documents\Projects\repo\encoredev-examples\ts\expressjs-migration\forklift-migration> encore run
  ✔ Building Encore application graph... Done!
  ✔ Analyzing service topology... Done!
  ⠙ Starting Encore application...

  Encore development server running!

  Your API is running at:     http://127.0.0.1:4000
  Development Dashboard URL:  http://localhost:9400/mpytq

C:\Users\melkmeshi\Documents\Projects\repo\encoredev-examples\ts\expressjs-migration\forklift-migration\app\app.ts:13
const odoo = new OdooJSONRpc({
             ^

TypeError: OdooJSONRpc is not a constructor
    at <anonymous> (C:\Users\melkmeshi\Documents\Projects\repo\encoredev-examples\ts\expressjs-migration\forklift-migration\app\app.ts:13:14)
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)

Node.js v22.9.0

I'm just trying it out and I thought to ask here if I did something wrong my code is :
import OdooJSONRpc from "@fernandoslim/odoo-jsonrpc";

const odoo = new OdooJSONRpc({
  baseUrl: `${process.env.ODOO_PROTOCOL!}://${process.env.ODOO_HOST!}`,
  port: Number(process.env.ODOO_PORT!),
  db: process.env.ODOO_DB!,
  username: process.env.ODOO_USERNAME!,
  apiKey: process.env.ODOO_APIKEY!,
});
odoo.connect();

**Comment by mwolfeu** [comment]
Bump.  Same problem.
Node/Ubuntu

**Comment by fernandoslim** [comment]
Hi, 

I think it is a tsconfig problem on your project, I don't know anything about encore but you can add OdooJSONRpc.ts to your project and import from it:
````
import OdooJSONRpc from './OdooJSONRpc';

const odoo = new OdooJSONRpc({
  baseUrl: 'https://your-odoo-instance.com',  
  port: 443,
  db: 'your_database_name',
  username: 'your_username', 
  password: 'your_password',
});
await odoo.connect();
const contacts = await odoo.read('res.partner', 1, ['name', 'email']);
console.log(contacts);
