### ISSUE TITLE
How to fetch the `user_id` of the authenticated user?

### ISSUE THREAD

**Issue by totzk9** [fernandoslim/odoo-jsonrpc#2]
[OdooAwait](https://github.com/vettloffah/odoo-await) had a way to fetch the user_id by returning it via `odoo.connect`.

Is there a simple way to fetch the `user_id` instead of reading from `res.users`?

**Comment by fernandoslim** [comment]
Thank you for your valuable feedback. I am pleased to inform you that version 1.6.0 has been released, incorporating your suggestions. Now, odoo.connect() will return an OdooAuthenticateResponse, which includes the complete response object from Odoo.

**Comment by totzk9** [comment]
@fernandoslim tysm. awesome package!
