### ISSUE TITLE
Is there a way to connect using the api key instead the pass?

### ISSUE THREAD

**Issue by JoeArenas** [fernandoslim/odoo-jsonrpc#5]
Hi, is there some way, like the showed in the following image using postman directly, to connect using the generated api-key instead of the user pass?
<img width="1308" alt="image" src="https://github.com/fernandoslim/odoo-jsonrpc/assets/49407293/5143e5dc-9db7-480b-ad8b-8062d8c93702">

**Comment by JoeArenas** [comment]
Analyzing carefully, I see that to handle requests with the /jsonrpc endpoint, requests must always be sent with a password and id, which is not within the scope of this library. I will close the isuue

**Comment by fernandoslim** [comment]
Hi @JoeArenas ,

Thank you for your question. It's an excellent point you've raised about API key authentication.

I'm pleased to inform you that as a result of your inquiry, I've investigated and implemented Odoo API key support in the latest release. Version 1.9.0 now includes API key authentication functionality.

Here's a quick example of how to use it:

```typescript
const odoo = new OdooJSONRpc({
  baseUrl: 'https://your-odoo-instance.com',
  port: 443,
  db: 'your-database',
  username: 'your-username',
  apiKey: 'your-api-key'
});

await odoo.connect();
